version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.3.0

workflows:
  version: 2
  dev:
    jobs: 
      - test:
          filters:
            branches:
              ignore: master
      - build_and_deploy:
          requires:
            - test
  prod:
    jobs: 
      - test:
          filters:
            branches:
              only: master
      - build_and_deploy:
          requires:
            - test

defaults:
  docker:
    - image: &executor circleci/python:3.8.5

jobs:
  test:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - run:
          name: Test step
          command: |
            echo "Run test command here"

  build_and_deploy:
    machine:
      docker_layer_caching: true
    environment:
      IMAGE_TAG: << pipeline.number >>
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: backend
          tag: $IMAGE_TAG
      - aws-ecs/update-service:
          family: test
          cluster-name: cluster
          container-image-name-updates: container=node,tag=$IMAGE_TAG
          verify-revision-is-deployed: true
          poll-interval: 5
          max-poll-attempts: 90